# Generated by Django 5.1 on 2024-08-26 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=254, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=254, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, default='D:\\Desktop\\SevakNews\\main\\media/default.jpg', upload_to='Users-photo/', verbose_name='Фото пользователя')),
                ('register_in', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('notification', models.BooleanField(default=False, verbose_name='Уведомления')),
                ('email_verify', models.BooleanField(default=False, verbose_name='Подтверждение почты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_base', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Данные пользователя',
                'verbose_name_plural': 'Пользовательские данные',
                'ordering': ['user'],
            },
        ),
    ]
