# Generated by Django 5.1 on 2024-08-26 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='photo',
            field=models.ImageField(blank=True, default='D:\\Desktop\\SevakNews\\main\\main/static/img/default_login.jpg', upload_to='Users-photo/', verbose_name='Фото пользователя'),
        ),
    ]
