# Generated by Django 5.1 on 2024-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_userbase_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='photo',
            field=models.ImageField(blank=True, default='D:\\Desktop\\SevakNews\\main\\media/default_login.jpg', upload_to='Users-photo/', verbose_name='Фото пользователя'),
        ),
    ]
